---
- name: Example Playbook
  hosts: all
  become: yes
  vars:
    etc_hosts_add_all_hosts: true
    openldap_base: "dc=ravnik,dc=home"
    openldap_domain_name: "{{ pri_domain_name }}"
    pri_domain_name: ravnik.home
  roles:
    - mrlesmithjr.openldap
